version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: suporter-frontend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT:-7080}:${PORT:-7080}"
    networks:
      - tirenn-net

networks:
  tirenn-net:
    external: true
