version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: suporter-frontend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:80"
